# Generated by Django 4.2.4 on 2023-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('src', models.CharField(max_length=31)),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('img_src', models.CharField(max_length=31)),
            ],
        ),
    ]
