# Generated by Django 4.2.4 on 2023-08-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_articles2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
