# Generated by Django 4.2.4 on 2023-09-01 08:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('article_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_id', to='app01.articles2')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
