# Generated by Django 4.2.4 on 2023-09-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_comments_article_id_comments_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
    ]
