# Generated by Django 4.2.4 on 2023-09-01 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_comments_article'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comments',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='app01.articles2'),
        ),
    ]
