# Generated by Django 4.2.4 on 2023-09-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_comments_managers_alter_comments_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles2',
            name='com_count',
            field=models.IntegerField(default=0),
        ),
    ]
