# Generated by Django 4.2.4 on 2023-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_articles2_com_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('name', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('art_count', models.IntegerField(default=0)),
            ],
        ),
    ]
