# Generated by Django 4.2.4 on 2023-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_sources'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sources',
        ),
        migrations.AddField(
            model_name='articles2',
            name='month',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='articles2',
            name='com_count',
            field=models.IntegerField(),
        ),
    ]
