# Generated by Django 4.2.4 on 2023-09-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_articles3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles3',
            name='month',
        ),
    ]
