# Generated by Django 4.2.4 on 2023-09-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_comments_article_delete_articles2'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles3',
            name='images',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
