# Generated by Django 4.2.4 on 2023-09-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_invertedindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invertedindex',
            name='id',
        ),
        migrations.AlterField(
            model_name='invertedindex',
            name='key',
            field=models.CharField(max_length=31, primary_key=True, serialize=False),
        ),
    ]
