# Generated by Django 4.2.4 on 2023-09-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_remove_invertedindex_id_alter_invertedindex_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='invertedindex',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invertedindex',
            name='key',
            field=models.CharField(max_length=31),
        ),
    ]
