# Generated by Django 4.2.4 on 2023-09-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_invertedindex_id_alter_invertedindex_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedIndex2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=31)),
                ('articles', models.TextField()),
            ],
        ),
    ]
